apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-jobs
spec:
  template:
    completions: 3
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never
