apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: pv-log
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
